[build]
  command = "npm run build"
  functions = "out_functions"
  publish = "out"

[build.environment]
    NODE_VERSION = "v18.17.0"
    NPM_VERSION = "8.19.4"

[[plugins]]
package = "@netlify/plugin-nextjs"
