[build]
command = "npm run build"
functions = "out_functions"
publish = "out_publish"

[build.environment]
NODE_VERSION = "v16.20.2"
NPM_VERSION = "8.19.4"

[[plugins]]
package = "@netlify/plugin-nextjs"
